version: '3.7'
services:
  backend:
    build : ./
    image: asset-backend:v1
    container_name: asset-backend_c
    ports:
      - 4000:4000
    volumes:
      - ./app:/src/app
    
    environment:
      NODE_ENV: development
    restart: always
   

